// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DentalClinicBooking_Project.Models.Domain;

public partial class Account
{
    public Guid AccountId { get; set; }

    public string Gmail { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int RoleId { get; set; }

    public virtual Admin Admin { get; set; }

    public virtual Dentist Dentist { get; set; }

    public virtual Owner Owner { get; set; }

    public virtual Patient Patient { get; set; }
}