// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DentalClinicBooking_Project.Models.Domain;

public partial class ClinicImage
{
    public Guid ImageId { get; set; }

    public string Image { get; set; }

    public Guid? ClinicId { get; set; }

    public virtual Clinic Clinic { get; set; }
}