// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DentalClinicBooking_Project.Models.Domain;

public partial class Clinic
{
    public Guid ClinicId { get; set; }

    public string ClinicName { get; set; }

    public string MainImage { get; set; }

    public string Description { get; set; }

    public Guid? OwnerId { get; set; }

    public virtual ICollection<Basic> Basics { get; set; } = new List<Basic>();

    public virtual ICollection<ClinicAppointmentSchedule> ClinicAppointmentSchedules { get; set; } = new List<ClinicAppointmentSchedule>();

    public virtual ICollection<ClinicImage> ClinicImages { get; set; } = new List<ClinicImage>();

    public virtual Owner Owner { get; set; }

    public virtual ICollection<SlotOfClinic> SlotOfClinics { get; set; } = new List<SlotOfClinic>();

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}