// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DentalClinicBooking_Project.Models.Domain;

public partial class Owner
{
    public Guid OwnerId { get; set; }

    public string OwnerName { get; set; }

    public string Experience { get; set; }

    public string Image { get; set; }

    public Guid? AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Clinic> Clinics { get; set; } = new List<Clinic>();
}