// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DentalClinicBooking_Project.Models.Domain;

public partial class Service
{
    public Guid ServiceId { get; set; }

    public string ServiceName { get; set; }

    public decimal? Price { get; set; }

    public virtual ICollection<ClinicAppointmentSchedule> ClinicAppointmentSchedules { get; set; } = new List<ClinicAppointmentSchedule>();

    public virtual ICollection<Clinic> Clinics { get; set; } = new List<Clinic>();
}