// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DentalClinicBooking_Project.Models.Domain;

public partial class SlotOfClinic
{
    public Guid SlotId { get; set; }

    public Guid ClinicId { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public virtual Clinic Clinic { get; set; }

    public virtual Slot Slot { get; set; }
}